#cloud-config
---
coreos:
  etcd2:
    discovery: "http://192.168.64.1:2379/v2/keys/discovery/f1900e470a289ee91ff6590730addfd3e55b1454"
    advertise-client-urls: "http://$public_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"
  fleet:
    public-ip: "$public_ipv4"
    metadata: "region=coupang"
  flannel:
    etcd_prefix: "/coreos.com/network"
  units:
    - name: "etcd2.service"
      command: "start"
    - name: "fleet.service"
      command: "start"
    - name: "flanneld.service"
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "172.24.0.0/16" }'
      command: "start"
    - name: "docker.service"
      command: "start"
      drop-ins:
        - name: 40-flannel.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBUT3fgzNa7m12Q8UYYIAAIWupiiE+OJtWbtPPvObUzYItsCp/SP7DHyPUnKaedSTJdruRpeo6fylGmKA/Xn30MJ0QTyRenh59ehURQnhduLYdQnMSZwHL2S6Myo7sCJ9Ono+6oR6aHtze7lU9AgzTcmMX/7Ma1FZREG58/R9jkGYAeyBPbZ75zZ1g6wPLFtGK3ScMvaRAh0gBvyNbe+L5/dsoYKNLG62SOZNPrillTnyC+vS5IpbdMWghyQRNwfsqhdZpcyCQQs3lHzppkKQl2SvWlVwkmmoWt3bRygVbdhFWlDV5hND+zZ+Ez8s0hOVX490+yd1zNa2TFEZh0nGd ethernuiel@sanultari.com"
